[workspace]
resolver = "3"
members = [
	"crates/cli/",
	"crates/embed/",
	"crates/formatter/",
	"crates/parser/",
]
exclude = ["crates/parser/fuzz/", "crates/embed/tests/fixtures/sqlx_app/"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.dependencies]
embed = { path = "crates/embed/" }
formatter = { path = "crates/formatter/" }
parser = { path = "crates/parser/" }
cstree = { version = "0.12", features = ["derive"] }
insta = "1"
