[workspace]
resolver = "3"
members = ["crates/parser", "crates/formatter", "crates/cli"]
exclude = ["crates/parser/fuzz"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
parser = { path = "crates/parser" }
formatter = { path = "crates/formatter" }
cstree = { version = "0.12", features = ["derive"] }
insta = "1"
