//! Generated keyword tables — do not edit by hand.
//!
//! Sources:
//! - Postgres `src/include/parser/kwlist.h`, branch REL_18_STABLE
//! - SQLite `tool/mkkeywordhash.c`, branch master
//!
//! Regenerate by re-fetching those files and rebuilding the arrays with
//! the same shape (name, category), sorted for binary search.

/// The four Postgres keyword categories from `kwlist.h`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PgKeywordCategory {
	Unreserved,
	ColName,
	TypeFuncName,
	Reserved,
}

/// All 494 Postgres keywords, sorted for binary search.
pub static PG_KEYWORDS: &[(&str, PgKeywordCategory)] = &[
	("abort", PgKeywordCategory::Unreserved),
	("absent", PgKeywordCategory::Unreserved),
	("absolute", PgKeywordCategory::Unreserved),
	("access", PgKeywordCategory::Unreserved),
	("action", PgKeywordCategory::Unreserved),
	("add", PgKeywordCategory::Unreserved),
	("admin", PgKeywordCategory::Unreserved),
	("after", PgKeywordCategory::Unreserved),
	("aggregate", PgKeywordCategory::Unreserved),
	("all", PgKeywordCategory::Reserved),
	("also", PgKeywordCategory::Unreserved),
	("alter", PgKeywordCategory::Unreserved),
	("always", PgKeywordCategory::Unreserved),
	("analyse", PgKeywordCategory::Reserved),
	("analyze", PgKeywordCategory::Reserved),
	("and", PgKeywordCategory::Reserved),
	("any", PgKeywordCategory::Reserved),
	("array", PgKeywordCategory::Reserved),
	("as", PgKeywordCategory::Reserved),
	("asc", PgKeywordCategory::Reserved),
	("asensitive", PgKeywordCategory::Unreserved),
	("assertion", PgKeywordCategory::Unreserved),
	("assignment", PgKeywordCategory::Unreserved),
	("asymmetric", PgKeywordCategory::Reserved),
	("at", PgKeywordCategory::Unreserved),
	("atomic", PgKeywordCategory::Unreserved),
	("attach", PgKeywordCategory::Unreserved),
	("attribute", PgKeywordCategory::Unreserved),
	("authorization", PgKeywordCategory::TypeFuncName),
	("backward", PgKeywordCategory::Unreserved),
	("before", PgKeywordCategory::Unreserved),
	("begin", PgKeywordCategory::Unreserved),
	("between", PgKeywordCategory::ColName),
	("bigint", PgKeywordCategory::ColName),
	("binary", PgKeywordCategory::TypeFuncName),
	("bit", PgKeywordCategory::ColName),
	("boolean", PgKeywordCategory::ColName),
	("both", PgKeywordCategory::Reserved),
	("breadth", PgKeywordCategory::Unreserved),
	("by", PgKeywordCategory::Unreserved),
	("cache", PgKeywordCategory::Unreserved),
	("call", PgKeywordCategory::Unreserved),
	("called", PgKeywordCategory::Unreserved),
	("cascade", PgKeywordCategory::Unreserved),
	("cascaded", PgKeywordCategory::Unreserved),
	("case", PgKeywordCategory::Reserved),
	("cast", PgKeywordCategory::Reserved),
	("catalog", PgKeywordCategory::Unreserved),
	("chain", PgKeywordCategory::Unreserved),
	("char", PgKeywordCategory::ColName),
	("character", PgKeywordCategory::ColName),
	("characteristics", PgKeywordCategory::Unreserved),
	("check", PgKeywordCategory::Reserved),
	("checkpoint", PgKeywordCategory::Unreserved),
	("class", PgKeywordCategory::Unreserved),
	("close", PgKeywordCategory::Unreserved),
	("cluster", PgKeywordCategory::Unreserved),
	("coalesce", PgKeywordCategory::ColName),
	("collate", PgKeywordCategory::Reserved),
	("collation", PgKeywordCategory::TypeFuncName),
	("column", PgKeywordCategory::Reserved),
	("columns", PgKeywordCategory::Unreserved),
	("comment", PgKeywordCategory::Unreserved),
	("comments", PgKeywordCategory::Unreserved),
	("commit", PgKeywordCategory::Unreserved),
	("committed", PgKeywordCategory::Unreserved),
	("compression", PgKeywordCategory::Unreserved),
	("concurrently", PgKeywordCategory::TypeFuncName),
	("conditional", PgKeywordCategory::Unreserved),
	("configuration", PgKeywordCategory::Unreserved),
	("conflict", PgKeywordCategory::Unreserved),
	("connection", PgKeywordCategory::Unreserved),
	("constraint", PgKeywordCategory::Reserved),
	("constraints", PgKeywordCategory::Unreserved),
	("content", PgKeywordCategory::Unreserved),
	("continue", PgKeywordCategory::Unreserved),
	("conversion", PgKeywordCategory::Unreserved),
	("copy", PgKeywordCategory::Unreserved),
	("cost", PgKeywordCategory::Unreserved),
	("create", PgKeywordCategory::Reserved),
	("cross", PgKeywordCategory::TypeFuncName),
	("csv", PgKeywordCategory::Unreserved),
	("cube", PgKeywordCategory::Unreserved),
	("current", PgKeywordCategory::Unreserved),
	("current_catalog", PgKeywordCategory::Reserved),
	("current_date", PgKeywordCategory::Reserved),
	("current_role", PgKeywordCategory::Reserved),
	("current_schema", PgKeywordCategory::TypeFuncName),
	("current_time", PgKeywordCategory::Reserved),
	("current_timestamp", PgKeywordCategory::Reserved),
	("current_user", PgKeywordCategory::Reserved),
	("cursor", PgKeywordCategory::Unreserved),
	("cycle", PgKeywordCategory::Unreserved),
	("data", PgKeywordCategory::Unreserved),
	("database", PgKeywordCategory::Unreserved),
	("day", PgKeywordCategory::Unreserved),
	("deallocate", PgKeywordCategory::Unreserved),
	("dec", PgKeywordCategory::ColName),
	("decimal", PgKeywordCategory::ColName),
	("declare", PgKeywordCategory::Unreserved),
	("default", PgKeywordCategory::Reserved),
	("defaults", PgKeywordCategory::Unreserved),
	("deferrable", PgKeywordCategory::Reserved),
	("deferred", PgKeywordCategory::Unreserved),
	("definer", PgKeywordCategory::Unreserved),
	("delete", PgKeywordCategory::Unreserved),
	("delimiter", PgKeywordCategory::Unreserved),
	("delimiters", PgKeywordCategory::Unreserved),
	("depends", PgKeywordCategory::Unreserved),
	("depth", PgKeywordCategory::Unreserved),
	("desc", PgKeywordCategory::Reserved),
	("detach", PgKeywordCategory::Unreserved),
	("dictionary", PgKeywordCategory::Unreserved),
	("disable", PgKeywordCategory::Unreserved),
	("discard", PgKeywordCategory::Unreserved),
	("distinct", PgKeywordCategory::Reserved),
	("do", PgKeywordCategory::Reserved),
	("document", PgKeywordCategory::Unreserved),
	("domain", PgKeywordCategory::Unreserved),
	("double", PgKeywordCategory::Unreserved),
	("drop", PgKeywordCategory::Unreserved),
	("each", PgKeywordCategory::Unreserved),
	("else", PgKeywordCategory::Reserved),
	("empty", PgKeywordCategory::Unreserved),
	("enable", PgKeywordCategory::Unreserved),
	("encoding", PgKeywordCategory::Unreserved),
	("encrypted", PgKeywordCategory::Unreserved),
	("end", PgKeywordCategory::Reserved),
	("enforced", PgKeywordCategory::Unreserved),
	("enum", PgKeywordCategory::Unreserved),
	("error", PgKeywordCategory::Unreserved),
	("escape", PgKeywordCategory::Unreserved),
	("event", PgKeywordCategory::Unreserved),
	("except", PgKeywordCategory::Reserved),
	("exclude", PgKeywordCategory::Unreserved),
	("excluding", PgKeywordCategory::Unreserved),
	("exclusive", PgKeywordCategory::Unreserved),
	("execute", PgKeywordCategory::Unreserved),
	("exists", PgKeywordCategory::ColName),
	("explain", PgKeywordCategory::Unreserved),
	("expression", PgKeywordCategory::Unreserved),
	("extension", PgKeywordCategory::Unreserved),
	("external", PgKeywordCategory::Unreserved),
	("extract", PgKeywordCategory::ColName),
	("false", PgKeywordCategory::Reserved),
	("family", PgKeywordCategory::Unreserved),
	("fetch", PgKeywordCategory::Reserved),
	("filter", PgKeywordCategory::Unreserved),
	("finalize", PgKeywordCategory::Unreserved),
	("first", PgKeywordCategory::Unreserved),
	("float", PgKeywordCategory::ColName),
	("following", PgKeywordCategory::Unreserved),
	("for", PgKeywordCategory::Reserved),
	("force", PgKeywordCategory::Unreserved),
	("foreign", PgKeywordCategory::Reserved),
	("format", PgKeywordCategory::Unreserved),
	("forward", PgKeywordCategory::Unreserved),
	("freeze", PgKeywordCategory::TypeFuncName),
	("from", PgKeywordCategory::Reserved),
	("full", PgKeywordCategory::TypeFuncName),
	("function", PgKeywordCategory::Unreserved),
	("functions", PgKeywordCategory::Unreserved),
	("generated", PgKeywordCategory::Unreserved),
	("global", PgKeywordCategory::Unreserved),
	("grant", PgKeywordCategory::Reserved),
	("granted", PgKeywordCategory::Unreserved),
	("greatest", PgKeywordCategory::ColName),
	("group", PgKeywordCategory::Reserved),
	("grouping", PgKeywordCategory::ColName),
	("groups", PgKeywordCategory::Unreserved),
	("handler", PgKeywordCategory::Unreserved),
	("having", PgKeywordCategory::Reserved),
	("header", PgKeywordCategory::Unreserved),
	("hold", PgKeywordCategory::Unreserved),
	("hour", PgKeywordCategory::Unreserved),
	("identity", PgKeywordCategory::Unreserved),
	("if", PgKeywordCategory::Unreserved),
	("ilike", PgKeywordCategory::TypeFuncName),
	("immediate", PgKeywordCategory::Unreserved),
	("immutable", PgKeywordCategory::Unreserved),
	("implicit", PgKeywordCategory::Unreserved),
	("import", PgKeywordCategory::Unreserved),
	("in", PgKeywordCategory::Reserved),
	("include", PgKeywordCategory::Unreserved),
	("including", PgKeywordCategory::Unreserved),
	("increment", PgKeywordCategory::Unreserved),
	("indent", PgKeywordCategory::Unreserved),
	("index", PgKeywordCategory::Unreserved),
	("indexes", PgKeywordCategory::Unreserved),
	("inherit", PgKeywordCategory::Unreserved),
	("inherits", PgKeywordCategory::Unreserved),
	("initially", PgKeywordCategory::Reserved),
	("inline", PgKeywordCategory::Unreserved),
	("inner", PgKeywordCategory::TypeFuncName),
	("inout", PgKeywordCategory::ColName),
	("input", PgKeywordCategory::Unreserved),
	("insensitive", PgKeywordCategory::Unreserved),
	("insert", PgKeywordCategory::Unreserved),
	("instead", PgKeywordCategory::Unreserved),
	("int", PgKeywordCategory::ColName),
	("integer", PgKeywordCategory::ColName),
	("intersect", PgKeywordCategory::Reserved),
	("interval", PgKeywordCategory::ColName),
	("into", PgKeywordCategory::Reserved),
	("invoker", PgKeywordCategory::Unreserved),
	("is", PgKeywordCategory::TypeFuncName),
	("isnull", PgKeywordCategory::TypeFuncName),
	("isolation", PgKeywordCategory::Unreserved),
	("join", PgKeywordCategory::TypeFuncName),
	("json", PgKeywordCategory::ColName),
	("json_array", PgKeywordCategory::ColName),
	("json_arrayagg", PgKeywordCategory::ColName),
	("json_exists", PgKeywordCategory::ColName),
	("json_object", PgKeywordCategory::ColName),
	("json_objectagg", PgKeywordCategory::ColName),
	("json_query", PgKeywordCategory::ColName),
	("json_scalar", PgKeywordCategory::ColName),
	("json_serialize", PgKeywordCategory::ColName),
	("json_table", PgKeywordCategory::ColName),
	("json_value", PgKeywordCategory::ColName),
	("keep", PgKeywordCategory::Unreserved),
	("key", PgKeywordCategory::Unreserved),
	("keys", PgKeywordCategory::Unreserved),
	("label", PgKeywordCategory::Unreserved),
	("language", PgKeywordCategory::Unreserved),
	("large", PgKeywordCategory::Unreserved),
	("last", PgKeywordCategory::Unreserved),
	("lateral", PgKeywordCategory::Reserved),
	("leading", PgKeywordCategory::Reserved),
	("leakproof", PgKeywordCategory::Unreserved),
	("least", PgKeywordCategory::ColName),
	("left", PgKeywordCategory::TypeFuncName),
	("level", PgKeywordCategory::Unreserved),
	("like", PgKeywordCategory::TypeFuncName),
	("limit", PgKeywordCategory::Reserved),
	("listen", PgKeywordCategory::Unreserved),
	("load", PgKeywordCategory::Unreserved),
	("local", PgKeywordCategory::Unreserved),
	("localtime", PgKeywordCategory::Reserved),
	("localtimestamp", PgKeywordCategory::Reserved),
	("location", PgKeywordCategory::Unreserved),
	("lock", PgKeywordCategory::Unreserved),
	("locked", PgKeywordCategory::Unreserved),
	("logged", PgKeywordCategory::Unreserved),
	("mapping", PgKeywordCategory::Unreserved),
	("match", PgKeywordCategory::Unreserved),
	("matched", PgKeywordCategory::Unreserved),
	("materialized", PgKeywordCategory::Unreserved),
	("maxvalue", PgKeywordCategory::Unreserved),
	("merge", PgKeywordCategory::Unreserved),
	("merge_action", PgKeywordCategory::ColName),
	("method", PgKeywordCategory::Unreserved),
	("minute", PgKeywordCategory::Unreserved),
	("minvalue", PgKeywordCategory::Unreserved),
	("mode", PgKeywordCategory::Unreserved),
	("month", PgKeywordCategory::Unreserved),
	("move", PgKeywordCategory::Unreserved),
	("name", PgKeywordCategory::Unreserved),
	("names", PgKeywordCategory::Unreserved),
	("national", PgKeywordCategory::ColName),
	("natural", PgKeywordCategory::TypeFuncName),
	("nchar", PgKeywordCategory::ColName),
	("nested", PgKeywordCategory::Unreserved),
	("new", PgKeywordCategory::Unreserved),
	("next", PgKeywordCategory::Unreserved),
	("nfc", PgKeywordCategory::Unreserved),
	("nfd", PgKeywordCategory::Unreserved),
	("nfkc", PgKeywordCategory::Unreserved),
	("nfkd", PgKeywordCategory::Unreserved),
	("no", PgKeywordCategory::Unreserved),
	("none", PgKeywordCategory::ColName),
	("normalize", PgKeywordCategory::ColName),
	("normalized", PgKeywordCategory::Unreserved),
	("not", PgKeywordCategory::Reserved),
	("nothing", PgKeywordCategory::Unreserved),
	("notify", PgKeywordCategory::Unreserved),
	("notnull", PgKeywordCategory::TypeFuncName),
	("nowait", PgKeywordCategory::Unreserved),
	("null", PgKeywordCategory::Reserved),
	("nullif", PgKeywordCategory::ColName),
	("nulls", PgKeywordCategory::Unreserved),
	("numeric", PgKeywordCategory::ColName),
	("object", PgKeywordCategory::Unreserved),
	("objects", PgKeywordCategory::Unreserved),
	("of", PgKeywordCategory::Unreserved),
	("off", PgKeywordCategory::Unreserved),
	("offset", PgKeywordCategory::Reserved),
	("oids", PgKeywordCategory::Unreserved),
	("old", PgKeywordCategory::Unreserved),
	("omit", PgKeywordCategory::Unreserved),
	("on", PgKeywordCategory::Reserved),
	("only", PgKeywordCategory::Reserved),
	("operator", PgKeywordCategory::Unreserved),
	("option", PgKeywordCategory::Unreserved),
	("options", PgKeywordCategory::Unreserved),
	("or", PgKeywordCategory::Reserved),
	("order", PgKeywordCategory::Reserved),
	("ordinality", PgKeywordCategory::Unreserved),
	("others", PgKeywordCategory::Unreserved),
	("out", PgKeywordCategory::ColName),
	("outer", PgKeywordCategory::TypeFuncName),
	("over", PgKeywordCategory::Unreserved),
	("overlaps", PgKeywordCategory::TypeFuncName),
	("overlay", PgKeywordCategory::ColName),
	("overriding", PgKeywordCategory::Unreserved),
	("owned", PgKeywordCategory::Unreserved),
	("owner", PgKeywordCategory::Unreserved),
	("parallel", PgKeywordCategory::Unreserved),
	("parameter", PgKeywordCategory::Unreserved),
	("parser", PgKeywordCategory::Unreserved),
	("partial", PgKeywordCategory::Unreserved),
	("partition", PgKeywordCategory::Unreserved),
	("passing", PgKeywordCategory::Unreserved),
	("password", PgKeywordCategory::Unreserved),
	("path", PgKeywordCategory::Unreserved),
	("period", PgKeywordCategory::Unreserved),
	("placing", PgKeywordCategory::Reserved),
	("plan", PgKeywordCategory::Unreserved),
	("plans", PgKeywordCategory::Unreserved),
	("policy", PgKeywordCategory::Unreserved),
	("position", PgKeywordCategory::ColName),
	("preceding", PgKeywordCategory::Unreserved),
	("precision", PgKeywordCategory::ColName),
	("prepare", PgKeywordCategory::Unreserved),
	("prepared", PgKeywordCategory::Unreserved),
	("preserve", PgKeywordCategory::Unreserved),
	("primary", PgKeywordCategory::Reserved),
	("prior", PgKeywordCategory::Unreserved),
	("privileges", PgKeywordCategory::Unreserved),
	("procedural", PgKeywordCategory::Unreserved),
	("procedure", PgKeywordCategory::Unreserved),
	("procedures", PgKeywordCategory::Unreserved),
	("program", PgKeywordCategory::Unreserved),
	("publication", PgKeywordCategory::Unreserved),
	("quote", PgKeywordCategory::Unreserved),
	("quotes", PgKeywordCategory::Unreserved),
	("range", PgKeywordCategory::Unreserved),
	("read", PgKeywordCategory::Unreserved),
	("real", PgKeywordCategory::ColName),
	("reassign", PgKeywordCategory::Unreserved),
	("recursive", PgKeywordCategory::Unreserved),
	("ref", PgKeywordCategory::Unreserved),
	("references", PgKeywordCategory::Reserved),
	("referencing", PgKeywordCategory::Unreserved),
	("refresh", PgKeywordCategory::Unreserved),
	("reindex", PgKeywordCategory::Unreserved),
	("relative", PgKeywordCategory::Unreserved),
	("release", PgKeywordCategory::Unreserved),
	("rename", PgKeywordCategory::Unreserved),
	("repeatable", PgKeywordCategory::Unreserved),
	("replace", PgKeywordCategory::Unreserved),
	("replica", PgKeywordCategory::Unreserved),
	("reset", PgKeywordCategory::Unreserved),
	("restart", PgKeywordCategory::Unreserved),
	("restrict", PgKeywordCategory::Unreserved),
	("return", PgKeywordCategory::Unreserved),
	("returning", PgKeywordCategory::Reserved),
	("returns", PgKeywordCategory::Unreserved),
	("revoke", PgKeywordCategory::Unreserved),
	("right", PgKeywordCategory::TypeFuncName),
	("role", PgKeywordCategory::Unreserved),
	("rollback", PgKeywordCategory::Unreserved),
	("rollup", PgKeywordCategory::Unreserved),
	("routine", PgKeywordCategory::Unreserved),
	("routines", PgKeywordCategory::Unreserved),
	("row", PgKeywordCategory::ColName),
	("rows", PgKeywordCategory::Unreserved),
	("rule", PgKeywordCategory::Unreserved),
	("savepoint", PgKeywordCategory::Unreserved),
	("scalar", PgKeywordCategory::Unreserved),
	("schema", PgKeywordCategory::Unreserved),
	("schemas", PgKeywordCategory::Unreserved),
	("scroll", PgKeywordCategory::Unreserved),
	("search", PgKeywordCategory::Unreserved),
	("second", PgKeywordCategory::Unreserved),
	("security", PgKeywordCategory::Unreserved),
	("select", PgKeywordCategory::Reserved),
	("sequence", PgKeywordCategory::Unreserved),
	("sequences", PgKeywordCategory::Unreserved),
	("serializable", PgKeywordCategory::Unreserved),
	("server", PgKeywordCategory::Unreserved),
	("session", PgKeywordCategory::Unreserved),
	("session_user", PgKeywordCategory::Reserved),
	("set", PgKeywordCategory::Unreserved),
	("setof", PgKeywordCategory::ColName),
	("sets", PgKeywordCategory::Unreserved),
	("share", PgKeywordCategory::Unreserved),
	("show", PgKeywordCategory::Unreserved),
	("similar", PgKeywordCategory::TypeFuncName),
	("simple", PgKeywordCategory::Unreserved),
	("skip", PgKeywordCategory::Unreserved),
	("smallint", PgKeywordCategory::ColName),
	("snapshot", PgKeywordCategory::Unreserved),
	("some", PgKeywordCategory::Reserved),
	("source", PgKeywordCategory::Unreserved),
	("sql", PgKeywordCategory::Unreserved),
	("stable", PgKeywordCategory::Unreserved),
	("standalone", PgKeywordCategory::Unreserved),
	("start", PgKeywordCategory::Unreserved),
	("statement", PgKeywordCategory::Unreserved),
	("statistics", PgKeywordCategory::Unreserved),
	("stdin", PgKeywordCategory::Unreserved),
	("stdout", PgKeywordCategory::Unreserved),
	("storage", PgKeywordCategory::Unreserved),
	("stored", PgKeywordCategory::Unreserved),
	("strict", PgKeywordCategory::Unreserved),
	("string", PgKeywordCategory::Unreserved),
	("strip", PgKeywordCategory::Unreserved),
	("subscription", PgKeywordCategory::Unreserved),
	("substring", PgKeywordCategory::ColName),
	("support", PgKeywordCategory::Unreserved),
	("symmetric", PgKeywordCategory::Reserved),
	("sysid", PgKeywordCategory::Unreserved),
	("system", PgKeywordCategory::Unreserved),
	("system_user", PgKeywordCategory::Reserved),
	("table", PgKeywordCategory::Reserved),
	("tables", PgKeywordCategory::Unreserved),
	("tablesample", PgKeywordCategory::TypeFuncName),
	("tablespace", PgKeywordCategory::Unreserved),
	("target", PgKeywordCategory::Unreserved),
	("temp", PgKeywordCategory::Unreserved),
	("template", PgKeywordCategory::Unreserved),
	("temporary", PgKeywordCategory::Unreserved),
	("text", PgKeywordCategory::Unreserved),
	("then", PgKeywordCategory::Reserved),
	("ties", PgKeywordCategory::Unreserved),
	("time", PgKeywordCategory::ColName),
	("timestamp", PgKeywordCategory::ColName),
	("to", PgKeywordCategory::Reserved),
	("trailing", PgKeywordCategory::Reserved),
	("transaction", PgKeywordCategory::Unreserved),
	("transform", PgKeywordCategory::Unreserved),
	("treat", PgKeywordCategory::ColName),
	("trigger", PgKeywordCategory::Unreserved),
	("trim", PgKeywordCategory::ColName),
	("true", PgKeywordCategory::Reserved),
	("truncate", PgKeywordCategory::Unreserved),
	("trusted", PgKeywordCategory::Unreserved),
	("type", PgKeywordCategory::Unreserved),
	("types", PgKeywordCategory::Unreserved),
	("uescape", PgKeywordCategory::Unreserved),
	("unbounded", PgKeywordCategory::Unreserved),
	("uncommitted", PgKeywordCategory::Unreserved),
	("unconditional", PgKeywordCategory::Unreserved),
	("unencrypted", PgKeywordCategory::Unreserved),
	("union", PgKeywordCategory::Reserved),
	("unique", PgKeywordCategory::Reserved),
	("unknown", PgKeywordCategory::Unreserved),
	("unlisten", PgKeywordCategory::Unreserved),
	("unlogged", PgKeywordCategory::Unreserved),
	("until", PgKeywordCategory::Unreserved),
	("update", PgKeywordCategory::Unreserved),
	("user", PgKeywordCategory::Reserved),
	("using", PgKeywordCategory::Reserved),
	("vacuum", PgKeywordCategory::Unreserved),
	("valid", PgKeywordCategory::Unreserved),
	("validate", PgKeywordCategory::Unreserved),
	("validator", PgKeywordCategory::Unreserved),
	("value", PgKeywordCategory::Unreserved),
	("values", PgKeywordCategory::ColName),
	("varchar", PgKeywordCategory::ColName),
	("variadic", PgKeywordCategory::Reserved),
	("varying", PgKeywordCategory::Unreserved),
	("verbose", PgKeywordCategory::TypeFuncName),
	("version", PgKeywordCategory::Unreserved),
	("view", PgKeywordCategory::Unreserved),
	("views", PgKeywordCategory::Unreserved),
	("virtual", PgKeywordCategory::Unreserved),
	("volatile", PgKeywordCategory::Unreserved),
	("when", PgKeywordCategory::Reserved),
	("where", PgKeywordCategory::Reserved),
	("whitespace", PgKeywordCategory::Unreserved),
	("window", PgKeywordCategory::Reserved),
	("with", PgKeywordCategory::Reserved),
	("within", PgKeywordCategory::Unreserved),
	("without", PgKeywordCategory::Unreserved),
	("work", PgKeywordCategory::Unreserved),
	("wrapper", PgKeywordCategory::Unreserved),
	("write", PgKeywordCategory::Unreserved),
	("xml", PgKeywordCategory::Unreserved),
	("xmlattributes", PgKeywordCategory::ColName),
	("xmlconcat", PgKeywordCategory::ColName),
	("xmlelement", PgKeywordCategory::ColName),
	("xmlexists", PgKeywordCategory::ColName),
	("xmlforest", PgKeywordCategory::ColName),
	("xmlnamespaces", PgKeywordCategory::ColName),
	("xmlparse", PgKeywordCategory::ColName),
	("xmlpi", PgKeywordCategory::ColName),
	("xmlroot", PgKeywordCategory::ColName),
	("xmlserialize", PgKeywordCategory::ColName),
	("xmltable", PgKeywordCategory::ColName),
	("year", PgKeywordCategory::Unreserved),
	("yes", PgKeywordCategory::Unreserved),
	("zone", PgKeywordCategory::Unreserved),
];

/// All 148 SQLite keywords (lowercase), sorted for binary search.
pub static SQLITE_KEYWORDS: &[&str] = &[
	"abort",
	"action",
	"add",
	"after",
	"all",
	"alter",
	"always",
	"analyze",
	"and",
	"as",
	"asc",
	"attach",
	"autoincrement",
	"before",
	"begin",
	"between",
	"by",
	"cascade",
	"case",
	"cast",
	"check",
	"collate",
	"column",
	"commit",
	"conflict",
	"constraint",
	"create",
	"cross",
	"current",
	"current_date",
	"current_time",
	"current_timestamp",
	"database",
	"default",
	"deferrable",
	"deferred",
	"delete",
	"desc",
	"detach",
	"distinct",
	"do",
	"drop",
	"each",
	"else",
	"end",
	"escape",
	"except",
	"exclude",
	"exclusive",
	"exists",
	"explain",
	"fail",
	"filter",
	"first",
	"following",
	"for",
	"foreign",
	"from",
	"full",
	"generated",
	"glob",
	"group",
	"groups",
	"having",
	"if",
	"ignore",
	"immediate",
	"in",
	"index",
	"indexed",
	"initially",
	"inner",
	"insert",
	"instead",
	"intersect",
	"into",
	"is",
	"isnull",
	"join",
	"key",
	"last",
	"left",
	"like",
	"limit",
	"match",
	"materialized",
	"natural",
	"no",
	"not",
	"nothing",
	"notnull",
	"null",
	"nulls",
	"of",
	"offset",
	"on",
	"or",
	"order",
	"others",
	"outer",
	"over",
	"partition",
	"plan",
	"pragma",
	"preceding",
	"primary",
	"query",
	"raise",
	"range",
	"recursive",
	"references",
	"regexp",
	"reindex",
	"release",
	"rename",
	"replace",
	"restrict",
	"returning",
	"right",
	"rollback",
	"row",
	"rows",
	"savepoint",
	"select",
	"set",
	"table",
	"temp",
	"temporary",
	"then",
	"ties",
	"to",
	"transaction",
	"trigger",
	"unbounded",
	"union",
	"unique",
	"update",
	"using",
	"vacuum",
	"values",
	"view",
	"virtual",
	"when",
	"where",
	"window",
	"with",
	"within",
	"without",
];

/// Postgres keyword category for a lowercase word, if it is one.
pub fn pg_keyword_category(word: &str) -> Option<PgKeywordCategory> {
	PG_KEYWORDS
		.binary_search_by(|(kw, _)| kw.cmp(&word))
		.ok()
		.map(|index| PG_KEYWORDS[index].1)
}

/// Is this word (compared ASCII-case-insensitively) a SQLite keyword?
pub fn is_sqlite_keyword(word: &str) -> bool {
	let lower = word.to_ascii_lowercase();
	SQLITE_KEYWORDS.binary_search(&lower.as_str()).is_ok()
}
