[package]
name = "cli"
version.workspace = true
edition.workspace = true

[lints]
workspace = true
[dependencies]
parser.workspace = true
formatter.workspace = true
rayon = "1.12.0"
similar = "3.1.1"
embed = { version = "0.1.0", path = "../embed" }

[[bin]]
name = "squill"
path = "src/main.rs"

[[bin]]
name = "corpus-report"
path = "src/bin/corpus_report.rs"
