[[embedded]]
include = ["**/*.lua"]
grammar = "https://github.com/tree-sitter-grammars/tree-sitter-lua/releases/download/v0.5.0/tree-sitter-lua.wasm"
query = ".config/squill/lsqlite3.scm"
dialect = "sqlite"
