//! Syntax kinds and tree type aliases.
//!
//! `SyntaxKind` is generated by build.rs from `syntax.def`.

// cstree's Syntax derive expands to an `unsafe impl` (the workspace
// otherwise denies unsafe_code), and lint attributes on the derived
// enum do not reach the expansion — allow at module level instead.
mod kinds {
	#![allow(unsafe_code)]
	include!(concat!(env!("OUT_DIR"), "/syntax_kinds.rs"));
}
pub use kinds::SyntaxKind;

/// Syntax tree node, resolved so token text is directly accessible.
pub type SyntaxNode = cstree::syntax::ResolvedNode<SyntaxKind>;
/// Syntax tree token, resolved so its text is directly accessible.
pub type SyntaxToken = cstree::syntax::ResolvedToken<SyntaxKind>;
/// A child element: either a node or a token.
pub type SyntaxElement<'a> = cstree::syntax::ResolvedElementRef<'a, SyntaxKind>;
